image: registry.gitlab.com/vasilinenko/rabbit-cms-module-blog

stages:
  - test

cache:
  paths:
    - vendor/

test:
  stage: test
  script:
    - cp .docker/app/conf.d/custom.ini /usr/local/etc/php/conf.d/custom.ini
    - composer i --dev --no-interaction
    - ./vendor/bin/phplint -v --no-interaction
    - ./vendor/bin/phpcs -v
    - ./vendor/bin/phpinsights -v --no-interaction
    - ./vendor/bin/psalm
    - ./vendor/bin/phpstan analyse
    - ./vendor/bin/phpmd src/ ansi phpmd.xml
    - ./vendor/bin/phpmetrics --report-html=var/phpmetrics ./src/
    - ./vendor/bin/phpunit -v --no-interaction --coverage-text --colors=never
    - ./vendor/bin/infection --threads=4 --only-covered

