version: '3.7'

services:
  app:
    build: .docker/app
    working_dir: /app
    volumes:
      - .:/app
      - ./.docker/app/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ~/.ssh:/root/.ssh
      - ~/.composer:/root/.composer
    tty: true